name: master_push

# Указываем тригер
on:
  - push
  - pull_request
    
jobs:
  build:

    # указываем среду
    runs-on: ubuntu-latest

    steps:
      # Для того что бы следующие команды работали с корнем проекта
      - name: Git clone
        uses: actions/checkout@v1

      - name: make test
        # Запускаем линтер
        run: |
          make lint
