name: master_push

# Controls when the action will run. Triggers the workflow on push or pull request 
# events but only for the master branch
on:
  - push
  - pull_request
    
jobs:
  build:

    # The type of machine to run the job on
    runs-on: ubuntu-latest

    steps:
      - name: make test
        # Install and build project
        run: |
          make install
