name: master_push

# Controls when the action will run. Triggers the workflow on push or pull request 
# events but only for the master branch
on:
  - push
  - pull_request
    
jobs:
  steps:
    - name: Linter
      run: |
        make lint
